config/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    # path('', include('AppNepthune.urls')),
    path('', views.first_page_view, name="authenticate"),
    path('student/', include('student.urls')),
    path('account/', include('account.urls')),
    path('sponsors/', include('sponsors.urls')),
    # path('<slug:slug>/scholarship/', include('scholarship.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

print("STATIC SETTING ROOT", static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

nepthune/config/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from ..account import views

urlpatterns = [
    # path('', include('AppNepthune.urls')),
    path('', views.first_page_view, name="authenticate"),
    path('student/', include('nepthune.student.urls')),
    path('account/', include('nepthune.account.urls')),
    path('sponsors/', include('nepthune.sponsors.urls')),
    # path('<slug:slug>/scholarship/', include('scholarship.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

print("STATIC SETTING ROOT", static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

nepthune/student/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'),
    path('infos-persos.html', views.infos_perso, name='infos'),
    path('modif-infos-persos.html', views.infos_perso, name='modif-infos'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('myfilters.html', views.student_filters_view, name='filtres'),
    path('notifications.html', views.notifications_view, name='notifications'),
    path('faq.html', views.faq_view, name='foire-aux-questions'),
    path('tests.html', views.base, name='tests'),
    #path("create", views)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'),
    path('infos-persos.html', views.infos_perso, name='infos'),
    path('modif-infos-persos.html', views.infos_perso, name='modif-infos'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('myfilters.html', views.student_filters_view, name='filtres'),
    path('notifications.html', views.notifications_view, name='notifications'),
    path('tests.html', views.base, name='tests'),
    #path("create", views)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nepthune/student/models.py
from django.db import models
from django.conf import settings
from django import forms
from django.forms import ModelForm
from ..account.models import CustomUser


# Create your models here.
 
     
class StudentName(models.Model):
    name = models.CharField("Prenom", max_length=30, default="")
    surname = models.CharField("Nom", max_length=30, default="")
    birthday = models.DateTimeField('Date de Naissance')
    
    def __str__(self):
        return '%s %s' % (self.name, self.surname)
    
    @property
    def full_name(self):
        "Returns the person's full name."
        return '%s %s' % (self.name, self.surname)
    
class StudentInformation(StudentName):
    user = models.OneToOneField(CustomUser, related_name="profile", on_delete=models.CASCADE)
    nationality = models.CharField("Nationalite",
                                   max_length=50, default="française")
    address = models.CharField("Adresse",
                               max_length=200)
    phone = models.CharField("N° téléphone", 
                             max_length=10, 
                             unique=True)
    studies = models.CharField("Domaine d'études", 
                               max_length=50, 
                               choices=settings.ETUDES, 
                               default=None)
    level = models.CharField("Niveau d'études", 
                             max_length=50, 
                             choices=settings.NIVEAU, 
                             default=None)
    



# class StudentForm(ModelForm):
#     class Meta:
#         model = StudentInformations
#         fields = ['name', 'surname', 'birthday', 'email', 
#                   'address', 'phone', 'studies', 'level']
        

class StudentFilter(models.Model):
    student = models.ForeignKey(StudentInformation, on_delete=models.CASCADE)
    amount = models.IntegerField()
    payment_date = models.DateField() 
    nb_payments = models.IntegerField(choices=zip(map(str, range(1, 5)), range(1, 5)))
    
    

nepthune/student/forms.py
from django import forms
from .models import *
# from ..config import constants
from django.conf import settings
from django.forms import ModelForm


class StudentForm(ModelForm):
    class Meta:
        model = StudentInformation
        fields = ['user', 'birthday',  'nationality', 
                  'address', 'phone', 'studies', 'level']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
class StudentFilterForm(ModelForm):
    class Meta:
        model = StudentFilter
        fields = ['amount', 'payment_date', 'nb_payments']
        # widgets = {'nb_payments': forms.MultipleChoiceField(choices=zip(map(str, range(1, 5)), range(1, 5)),
        #                                     required=False, 
        #                                     label="Nombre limite de Versements",
        #                                     widget=forms.RadioSelect) }
        

class NameForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Prénom", 'style':"width:300px;", 'class':'form-control'}))
    surname = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Nom", 'style':"width:300px;", 'class':'form-control'}))
    birthday = forms.DateTimeField(widget=forms.SelectDateWidget(years=[str(i) for i in range(1900, 2023)], attrs={ 'style':"max-width:300px;"}))
    email = forms.EmailField(max_length=30, widget=forms.EmailInput(attrs={'placeholder': "adresse mail", 'style':"max-width:300px;", 'class':'form-control'}))
    address = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': "ex: 270 rue Saint-Jacques 75005 Paris", 'style':"max-width:300px;", 'class':'form-control'}))
    phone = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': "Téléphone", 'style':"max-width:300px; height:30px;", 'class':'form-control'}))
    studies = forms.ChoiceField(label="Domaine d'études", widget=forms.RadioSelect, choices=settings.ETUDES)
    level = forms.ChoiceField(label="Niveau d'études", widget=forms.RadioSelect, choices=settings.NIVEAU)

        

student/forms.py
from django import forms
from .models import *
# from ..config import constants
from django.conf import settings
from django.forms import ModelForm


class StudentForm(ModelForm):
    class Meta:
        model = StudentInformation
        fields = ['name', 'surname', 'birthday', 'email', 'nationality', 
                  'address', 'phone', 'studies', 'level', 'username']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        
class StudentFilterForm(ModelForm):
    class Meta:
        model = StudentFilter
        fields = ['amount', 'payment_date', 'nb_payments']
        # widgets = {'nb_payments': forms.MultipleChoiceField(choices=zip(map(str, range(1, 5)), range(1, 5)),
        #                                     required=False, 
        #                                     label="Nombre limite de Versements",
        #                                     widget=forms.RadioSelect) }
        

class NameForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Prénom", 'style':"width:300px;", 'class':'form-control'}))
    surname = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Nom", 'style':"width:300px;", 'class':'form-control'}))
    birthday = forms.DateTimeField(widget=forms.SelectDateWidget(years=[str(i) for i in range(1900, 2023)], attrs={ 'style':"max-width:300px;"}))
    email = forms.EmailField(max_length=30, widget=forms.EmailInput(attrs={'placeholder': "adresse mail", 'style':"max-width:300px;", 'class':'form-control'}))
    address = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': "ex: 270 rue Saint-Jacques 75005 Paris", 'style':"max-width:300px;", 'class':'form-control'}))
    phone = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': "Téléphone", 'style':"max-width:300px; height:30px;", 'class':'form-control'}))
    studies = forms.ChoiceField(label="Domaine d'études", widget=forms.RadioSelect, choices=settings.ETUDES)
    level = forms.ChoiceField(label="Niveau d'études", widget=forms.RadioSelect, choices=settings.NIVEAU)

        

nepthune/student/views.py
from django.shortcuts import render 

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.conf import settings
from django.http import HttpResponseRedirect

from .models import *
from .forms import *

@login_required(login_url="/account/login/")
def index(request):
    if request.user.is_authenticated:
        print("\n You are logged as {}\n".format(request.user), "\n", request)
        latest_student_list = StudentInformation.objects.order_by('-birthday')[:5]
        latest_student_list = StudentName.objects.order_by('-birthday')[:5]
        context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,
            'student': latest_student_list,   
        }
        return render(request, 'student/inscrit.html', context)
    
def base(request):
    context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,  
        }
    return render(request, 'student/tests.html', context)
    
    

def detail(request, student_id):
    try:
        context_student = StudentInformation.get(id=student_id)
    except StudentInformation.DoesNotExist:
        raise Http404("Cette élève n'est pas inscrit dans la BDD")
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        "student": context_student
    }
    return render(request, 'student/default.html', context)

def infos_perso(request):
    print(" \n\n",  "Request")
    a = request.__dict__
    print(request.user, a.keys(), "\n", a["environ"]["USERNAME"], a["environ"]["USERPROFILE"] )
    
    student_initial = StudentInformation.objects.get(user=request.user)
    if request.method == 'POST':
        try:
        # create a form instance and populate it with data from the request:
            form = StudentForm(request.POST, instance=student_initial)
        except:
            print("Student is not correctly registered")
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = StudentForm(instance=student_initial)
        
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/infos-persos.html', context)


def student_filters_view(request):
    
    # On rentre nos preferences pour la première fois
    if request.method == "POST":
        form = StudentFilterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/thanks/')
    else:
        form = StudentFilterForm()
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/myfilters.html', context)

def modif_infos_perso(request):
    pass

def notifications_view(request):
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
    }
    return render(request, 'student/notifications.html', context)

def faq_view(request):
    
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
    }
    return render(request, 'student/faq.html', context)



#################################################################
#               SCHOLARSHIPS
################################################################


def scholarships_view(request):
    pass

student/views.py
from django.shortcuts import render 

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.conf import settings
from django.http import HttpResponseRedirect

from .models import *
from .forms import *

@login_required(login_url="/account/login/")
def index(request):
    if request.user.is_authenticated:
        print("\n You are logged as {}\n".format(request.user), "\n", request)
        print("\n  \n", request.__dict__, "\n \n")
        print("\n  \n", request.__dict__.keys(), "\n \n")
        latest_student_list = StudentInformation.objects.order_by('-birthday')[:5]
        latest_student_list = StudentName.objects.order_by('-birthday')[:5]
        context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,
            'student': latest_student_list,   
        }
        return render(request, 'student/inscrit.html', context)
    
def base(request):
    context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,  
        }
    return render(request, 'student/tests.html', context)
    
    

def detail(request, student_id):
    try:
        context_student = StudentInformation.get(id=student_id)
    except StudentInformation.DoesNotExist:
        raise Http404("Cette élève n'est pas inscrit dans la BDD")
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        "student": context_student
    }
    return render(request, 'student/default.html', context)

def infos_perso(request):
    student_initial = StudentInformation.objects.get(username=request.user)
    if request.method == 'POST':
        if student_initial is not None:
        # create a form instance and populate it with data from the request:
            form = StudentForm(request.POST)
        else:
            form = StudentForm(request.POST, instance=student_initial)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = StudentForm(instance=student_initial)
        
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/infos-persos.html', context)


def student_filters_view(request):
    
    # On rentre nos preferences pour la première fois
    if request.method == "POST":
        form = StudentFilterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/thanks/')
    else:
        form = StudentFilterForm()
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/myfilters.html', context)

def modif_infos_perso(request):
    pass

def notifications_view(request):
    return render(request, 'student/notifications.html')

#################################################################
#               SCHOLARSHIPS
################################################################


def scholarships_view(request):
    pass

templates/student/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  {% block title %}<title>Nepthune</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'/>
  <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet"/>
  <link rel="shortcut icon" type="image/ico" href="{% static 'student/favicon.ico' %}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link href="https://unpkg.com/css-pro-layout/dist/css/css-pro-layout.min.css" rel="stylesheet" />

  <!-- Add additional CSS in static file -->
  <link  rel="stylesheet" type='text/css' href="{% static 'student/style.css' %}"  />
  <!-- type='text/css' -->
</head>
<style>
    span.menu-title {
    text-decoration: none;
  }
  .navbar-text {
    font-family: 'Poppins', sans-serif;
        font-weight: 400;
        color:rgb(3, 84, 108) !important;
  }
</style>
<body>
  <div class="layout has-sidebar fixed-sidebar fixed-header" id="current-sidebar">
          <!-- style="transition: transform 1s;"> -->
    <aside id="sidebar" class="sidebar break-point-lg has-bg-image">
      <a id="btn-collapse" class="sidebar-collapser"><i class="ri-arrow-left-s-line"></i></a>
      <!-- {% block sidebar %} -->
      {% include "./includes/sidebar.html" with sidebar_titles=sidebar_contents %}    
     <!-- {% endblock %} -->
    </aside>
    <div id="overlay" class="overlay"></div>
      <div class="layout">
        <header class="header">
          {% include "./includes/navigation.html" with navbar_titles=navbar_contents%}
        </header>
        <main class="content">
          <a id="btn-toggle" href="#" class="sidebar-toggler break-point-lg">
            <i class="ri-menu-line ri-xl"></i>
          </a>
          {% block content %}{% endblock %}
        </main>
        <div class="overlay"></div>
      </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
 <script type="module" src="{% static 'student/includes/js/@popperjs/core/lib/createPopper.js' %}"></script>
  <script type="module" src="{% static 'student/includes/js/sidebar.js' %}"></script>
</body>
</html>

templates/student/faq.html
{% extends 'student/base.html' %}

{% block content %}

{% endblock %}

templates/student/infos-persos.html
{% extends 'student/base.html' %}

{% block content %}
<h1>Vos informations personnelles</h1>
<button type="button" class="btn btn-primary">Modifier mes informations</button>


<style>
      body {
        /* font-style: medium; */
        font-family: 'Poppins', sans-serif;
      }
      h1 {
        color: rgba(5, 21, 79, 0.92);
      }
      .form-control {
        font-style: medium;
        font-family: 'Poppins', sans-serif;
      }
      ul {
        list-style-type: none;
        font-weight: 600;
      }
      ul li .fieldWrapper {
        font-style: medium;
        margin-bottom: 10px;
      }

      .btn {
        text-align: center;
        width: 10%;
        
      }

      input[type=button], input[type=reset] {
        margin-top: 40px;
        margin-left: 40px;
        font-size: 1em;
        font-style: bold;
        color: white;
        background-color: rgb(20, 115, 192);
        cursor: pointer;
        border-radius: 0.4em;
        margin-left: 600px;
        margin-top: -50px;
        padding: 10px 16px;
      }

      input[type=text], input[type=radio], input[type=email] {
        width: 350px;
        max-width: 350px;
      } 
  /* input[type="text"] > span {
    display: block;
    position: relative;
    margin-bottom: 10px;
  } */
</style>
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
{% endblock %}

templates/student/inscrit.html
{% extends 'student/base.html' %}

{% block content %}
    {% if student %}
        <ul>
            {% for stud in student %}
                <li> {{ stud.surname }} {{ stud.name }}: {{ stud.birthday }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No student registered at this id.</p>
    {% endif %}
{% endblock %}

templates/student/modif-infos-persos.html
{% extends 'student/base.html' %}

{% block content %}
<h1 style="margin-bottom: 0.5em; font-family: 'Poppins', sans-serif;">Vos informations personnelles</h1>
{% if form %}
      <!-- <tr style="display:flex;">
      <td>Niveau d'études: </td><br><br>
      <td><input type="radio" name="studies" value="BTS">BTS</td>
      <td><input type="radio" name="studies" value="BEP">BEP</td>
      <td><input type="radio" name="studies" value="CAP">CAP</td>
      <td><input type="radio" name="studies" value="L1">Licence 1</td>
      <td><input type="radio" name="studies" value="L2">Licence 2</td>
      <td><input type="radio" name="studies" value="L3">Licence 3</td>
      <td><input type="radio" name="studies" value="M1">Master 1</td>
      <td><input type="radio" name="studies" value="M2">Master 2</td>
      <td><input type="radio" name="studies" value="Doctorant">Doctorat</td>
      <td><input type="radio" name="studies" value="other">Autres</td>
    </tr>
    </table>
      <input type="submit" name="submit" value="Sauvegarder">  
    </form>  -->
    <form action="{% url 'student:index' %}" method="post">
        {% csrf_token %}
        <ul>
        {% for field in form %}
        <li>
        <div class="fieldWrapper">
            <!-- {{ field.errors }} -->
            {{ field.label_tag }}<br>{{ field }}
        </div></li>
        {% endfor %}
      </ul>
    
      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% endif %}
      <input type="button" value="Sauvegarder">
    </form>
    
{% else %}
    <p>No student registered at this id.</p>
{% endif %}
<style>
      body {
        font-style: medium;
        font-family: 'Poppins', sans-serif;
        color: rgba(5, 21, 79, 0.92);
      }
      .form-control {
        font-style: medium;
        font-family: 'Poppins', sans-serif;
      }
      ul {
        list-style-type: none;
        font-weight: 600;
      }
      ul li .fieldWrapper {
        font-style: medium;
        margin-bottom: 10px;
      }

      input[type=button], input[type=reset] {
        margin-top: 40px;
        margin-left: 40px;
        font-size: 1em;
        font-style: bold;
        color: white;
        background-color: rgb(20, 115, 192);
        cursor: pointer;
        border-radius: 0.4em;
        margin-left: 600px;
        margin-top: -50px;
        padding: 10px 16px;
      }

      input[type=text], input[type=radio], input[type=email] {
        width: 350px;
        max-width: 350px;
      } 
  /* input[type="text"] > span {
    display: block;
    position: relative;
    margin-bottom: 10px;
  } */
</style>
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
{% endblock %}

templates/student/myfilters.html
{% extends 'student/base.html' %}

{% block content %}
<h1 style="margin-bottom: 0.5em; font-family: 'Poppins', sans-serif;">Modifier Mes Filtres</h1>
{% if form %}
    <form action="{% url 'student:filtres' %}" method="post">
        {% csrf_token %}
        <ul>
        {% for field in form %}
        <li>
        <div class="fieldWrapper">
            <!-- {{ field.errors }} -->
            {{ field.label_tag }}<br>{{ field }}
        </div></li>
        {% endfor %}
      </ul>
    
      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% endif %}
      <input type="button" value="Sauvegarder">
    </form>
    
{% else %}
    <p>No student registered at this id.</p>
{% endif %}
<style>
      body {
        font-style: medium;
        font-family: 'Poppins', sans-serif;
        color: rgba(5, 21, 79, 0.92);
      }
      .form-control {
        font-style: medium;
        font-family: 'Poppins', sans-serif;
      }
      ul {
        list-style-type: none;
        font-weight: 600;
      }
      ul li .fieldWrapper {
        font-style: medium;
        margin-bottom: 10px;
      }

      input[type=button], input[type=reset] {
        margin-top: 40px;
        margin-left: 40px;
        font-size: 1em;
        font-style: bold;
        color: white;
        background-color: rgb(20, 115, 192);
        cursor: pointer;
        border-radius: 0.4em;
        margin-left: 600px;
        margin-top: -50px;
        padding: 10px 16px;
      }

      input[type=text], input[type=radio], input[type=email] {
        width: 350px;
        max-width: 350px;
      } 
  /* input[type="text"] > span {
    display: block;
    position: relative;
    margin-bottom: 10px;
  } */
</style>
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
{% endblock %}

templates/student/tests.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  {% block title %}<title>Nepthune</title>{% endblock %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet"/>
  <link rel="shortcut icon" type="image/ico" href="{% static 'student/favicon.ico' %}" />
  <link  href="{% static 'student/test_style.css' %}" rel="stylesheet" />
  <!-- type='text/css' -->
</head>
<body>
  <div class="layout has-sidebar fixed-sidebar fixed-header">
    <aside id="sidebar" class="sidebar break-point-lg has-bg-image">
      <a id="btn-collapse" class="sidebar-collapser"><i class="ri-arrow-left-s-line"></i></a>
      {% include "./includes/sidebar.html" with sidebar_titles=sidebar_contents %}
    </aside>
    <div id="overlay" class="overlay"></div>
    <div class="layout">
      <header class="header">
        {% include "./includes/navigation.html" with navbar_titles=navbar_contents %}
      </header>
      <main class="content">
        <a id="btn-toggle" href="#" class="sidebar-toggler break-point-lg">
          <i class="ri-menu-line ri-xl"></i>
        </a>
      </main>
      <div id="overlay" class="overlay"></div>
    </div>
  </div>
</body>
  <script type="module" src="{% static 'student/includes/js/sidebar.js' %}"></script>
</html>