account/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'account'
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('authenticate/', views.first_page_view, name="authenticate"),
    path('le_projet/', views.project_view, name="projet"),
    path('a_propos/', views.purpose_view, name="propos"),
    path('agir_avec_nous/', views.act_view, name="agir"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    # path('', include('AppNepthune.urls')),
    path('', views.first_page_view, name="authenticate"),
    path('student/', include('student.urls')),
    path('account/', include('account.urls')),
    path('sponsors/', include('sponsors.urls')),
    # path('<slug:slug>/scholarship/', include('scholarship.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

print("STATIC SETTING ROOT", static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

nepthune/config/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from ..account import views

urlpatterns = [
    # path('', include('AppNepthune.urls')),
    path('', views.first_page_view, name="authenticate"),
    path('student/', include('nepthune.student.urls')),
    path('account/', include('nepthune.account.urls')),
    path('sponsors/', include('nepthune.sponsors.urls')),
    # path('<slug:slug>/scholarship/', include('scholarship.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

print("STATIC SETTING ROOT", static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

nepthune/student/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'),
    path('infos-persos.html', views.infos_perso, name='infos'),
    path('modif-infos-persos.html', views.infos_perso, name='modif-infos'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('myfilters.html', views.student_filters_view, name='filtres'),
    path('notifications.html', views.notifications_view, name='notifications'),
    path('faq.html', views.faq_view, name='foire-aux-questions'),
    path('tests.html', views.base, name='tests'),
    #path("create", views)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'),
    path('infos-persos.html', views.infos_perso, name='infos'),
    path('modif-infos-persos.html', views.infos_perso, name='modif-infos'),
    path('<int:student_id>/', views.detail, name='detail'),
    path('myfilters.html', views.student_filters_view, name='filtres'),
    path('notifications.html', views.notifications_view, name='notifications'),
    path('tests.html', views.base, name='tests'),
    #path("create", views)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nepthune/student/models.py
from django.db import models
from django.conf import settings
from django import forms
from django.forms import ModelForm
from ..account.models import CustomUser


# Create your models here.
 
     
class StudentName(models.Model):
    name = models.CharField("Prenom", max_length=30, default="")
    surname = models.CharField("Nom", max_length=30, default="")
    birthday = models.DateTimeField('Date de Naissance')
    
    def __str__(self):
        return '%s %s' % (self.name, self.surname)
    
    @property
    def full_name(self):
        "Returns the person's full name."
        return '%s %s' % (self.name, self.surname)
    
class StudentInformation(StudentName):
    user = models.OneToOneField(CustomUser, related_name="profile", on_delete=models.CASCADE)
    nationality = models.CharField("Nationalite",
                                   max_length=50, default="française")
    address = models.CharField("Adresse",
                               max_length=200)
    phone = models.CharField("N° téléphone", 
                             max_length=10, 
                             unique=True)
    studies = models.CharField("Domaine d'études", 
                               max_length=50, 
                               choices=settings.ETUDES, 
                               default=None)
    level = models.CharField("Niveau d'études", 
                             max_length=50, 
                             choices=settings.NIVEAU, 
                             default=None)
    



# class StudentForm(ModelForm):
#     class Meta:
#         model = StudentInformations
#         fields = ['name', 'surname', 'birthday', 'email', 
#                   'address', 'phone', 'studies', 'level']
        

class StudentFilter(models.Model):
    student = models.ForeignKey(StudentInformation, on_delete=models.CASCADE)
    amount = models.IntegerField()
    payment_date = models.DateField() 
    nb_payments = models.IntegerField(choices=zip(map(str, range(1, 5)), range(1, 5)))
    
    

nepthune/student/forms.py
from django import forms
from .models import *
# from ..config import constants
from django.conf import settings
from django.forms import ModelForm


class StudentForm(ModelForm):
    class Meta:
        model = StudentInformation
        fields = ['user', 'birthday',  'nationality', 
                  'address', 'phone', 'studies', 'level']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
class StudentFilterForm(ModelForm):
    class Meta:
        model = StudentFilter
        fields = ['amount', 'payment_date', 'nb_payments']
        # widgets = {'nb_payments': forms.MultipleChoiceField(choices=zip(map(str, range(1, 5)), range(1, 5)),
        #                                     required=False, 
        #                                     label="Nombre limite de Versements",
        #                                     widget=forms.RadioSelect) }
        

class NameForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Prénom", 'style':"width:300px;", 'class':'form-control'}))
    surname = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Nom", 'style':"width:300px;", 'class':'form-control'}))
    birthday = forms.DateTimeField(widget=forms.SelectDateWidget(years=[str(i) for i in range(1900, 2023)], attrs={ 'style':"max-width:300px;"}))
    email = forms.EmailField(max_length=30, widget=forms.EmailInput(attrs={'placeholder': "adresse mail", 'style':"max-width:300px;", 'class':'form-control'}))
    address = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': "ex: 270 rue Saint-Jacques 75005 Paris", 'style':"max-width:300px;", 'class':'form-control'}))
    phone = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': "Téléphone", 'style':"max-width:300px; height:30px;", 'class':'form-control'}))
    studies = forms.ChoiceField(label="Domaine d'études", widget=forms.RadioSelect, choices=settings.ETUDES)
    level = forms.ChoiceField(label="Niveau d'études", widget=forms.RadioSelect, choices=settings.NIVEAU)

        

student/forms.py
from django import forms
from .models import *
# from ..config import constants
from django.conf import settings
from django.forms import ModelForm


class StudentForm(ModelForm):
    class Meta:
        model = StudentInformation
        fields = ['name', 'surname', 'birthday', 'email', 'nationality', 
                  'address', 'phone', 'studies', 'level', 'username']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        
class StudentFilterForm(ModelForm):
    class Meta:
        model = StudentFilter
        fields = ['amount', 'payment_date', 'nb_payments']
        # widgets = {'nb_payments': forms.MultipleChoiceField(choices=zip(map(str, range(1, 5)), range(1, 5)),
        #                                     required=False, 
        #                                     label="Nombre limite de Versements",
        #                                     widget=forms.RadioSelect) }
        

class NameForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Prénom", 'style':"width:300px;", 'class':'form-control'}))
    surname = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': "Nom", 'style':"width:300px;", 'class':'form-control'}))
    birthday = forms.DateTimeField(widget=forms.SelectDateWidget(years=[str(i) for i in range(1900, 2023)], attrs={ 'style':"max-width:300px;"}))
    email = forms.EmailField(max_length=30, widget=forms.EmailInput(attrs={'placeholder': "adresse mail", 'style':"max-width:300px;", 'class':'form-control'}))
    address = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': "ex: 270 rue Saint-Jacques 75005 Paris", 'style':"max-width:300px;", 'class':'form-control'}))
    phone = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': "Téléphone", 'style':"max-width:300px; height:30px;", 'class':'form-control'}))
    studies = forms.ChoiceField(label="Domaine d'études", widget=forms.RadioSelect, choices=settings.ETUDES)
    level = forms.ChoiceField(label="Niveau d'études", widget=forms.RadioSelect, choices=settings.NIVEAU)

        

nepthune/student/views.py
from django.shortcuts import render 

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.conf import settings
from django.http import HttpResponseRedirect

from .models import *
from .forms import *

@login_required(login_url="/account/login/")
def index(request):
    if request.user.is_authenticated:
        print("\n You are logged as {}\n".format(request.user), "\n", request)
        latest_student_list = StudentInformation.objects.order_by('-birthday')[:5]
        latest_student_list = StudentName.objects.order_by('-birthday')[:5]
        context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,
            'student': latest_student_list,   
        }
        return render(request, 'student/inscrit.html', context)
    
def base(request):
    context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,  
        }
    return render(request, 'student/tests.html', context)
    
    

def detail(request, student_id):
    try:
        context_student = StudentInformation.get(id=student_id)
    except StudentInformation.DoesNotExist:
        raise Http404("Cette élève n'est pas inscrit dans la BDD")
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        "student": context_student
    }
    return render(request, 'student/default.html', context)

def infos_perso(request):
    print(" \n\n",  "Request")
    a = request.__dict__
    print(request.user, a.keys(), "\n", a["environ"]["USERNAME"], a["environ"]["USERPROFILE"] )
    
    student_initial = StudentInformation.objects.get(user=request.user)
    if request.method == 'POST':
        try:
        # create a form instance and populate it with data from the request:
            form = StudentForm(request.POST, instance=student_initial)
        except:
            print("Student is not correctly registered")
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = StudentForm(instance=student_initial)
        
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/infos-persos.html', context)


def student_filters_view(request):
    
    # On rentre nos preferences pour la première fois
    if request.method == "POST":
        form = StudentFilterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/thanks/')
    else:
        form = StudentFilterForm()
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/myfilters.html', context)

def modif_infos_perso(request):
    pass

def notifications_view(request):
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
    }
    return render(request, 'student/notifications.html', context)

def faq_view(request):
    
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
    }
    return render(request, 'student/faq.html', context)



#################################################################
#               SCHOLARSHIPS
################################################################


def scholarships_view(request):
    pass

student/views.py
from django.shortcuts import render 

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.conf import settings
from django.http import HttpResponseRedirect

from .models import *
from .forms import *

@login_required(login_url="/account/login/")
def index(request):
    if request.user.is_authenticated:
        print("\n You are logged as {}\n".format(request.user), "\n", request)
        print("\n  \n", request.__dict__, "\n \n")
        print("\n  \n", request.__dict__.keys(), "\n \n")
        latest_student_list = StudentInformation.objects.order_by('-birthday')[:5]
        latest_student_list = StudentName.objects.order_by('-birthday')[:5]
        context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,
            'student': latest_student_list,   
        }
        return render(request, 'student/inscrit.html', context)
    
def base(request):
    context = {
            'sidebar_contents': settings.SIDEBAR_TITLES,
            'navbar_contents': settings.NAV_TITLES,  
        }
    return render(request, 'student/tests.html', context)
    
    

def detail(request, student_id):
    try:
        context_student = StudentInformation.get(id=student_id)
    except StudentInformation.DoesNotExist:
        raise Http404("Cette élève n'est pas inscrit dans la BDD")
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        "student": context_student
    }
    return render(request, 'student/default.html', context)

def infos_perso(request):
    student_initial = StudentInformation.objects.get(username=request.user)
    if request.method == 'POST':
        if student_initial is not None:
        # create a form instance and populate it with data from the request:
            form = StudentForm(request.POST)
        else:
            form = StudentForm(request.POST, instance=student_initial)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = StudentForm(instance=student_initial)
        
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/infos-persos.html', context)


def student_filters_view(request):
    
    # On rentre nos preferences pour la première fois
    if request.method == "POST":
        form = StudentFilterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/thanks/')
    else:
        form = StudentFilterForm()
    context = {
        'sidebar_contents': settings.SIDEBAR_TITLES,
        'navbar_contents': settings.NAV_TITLES,
        'form': form,
    }
    return render(request, 'student/myfilters.html', context)

def modif_infos_perso(request):
    pass

def notifications_view(request):
    return render(request, 'student/notifications.html')

#################################################################
#               SCHOLARSHIPS
################################################################


def scholarships_view(request):
    pass

templates/student/includes/footer.html
<footer class="footer">
    <small style="margin-bottom: 20px; display: inline-block">
      © 2023 made with
      <span style="color: red; font-size: 18px">&#10084;</span> by -
      <a target="_blank" href="https://azouaoui.netlify.com"> Mohamed Azouaoui </a>
    </small>
    <br />
    <div class="social-links">
      <a href="https://github.com/azouaoui-med" target="_blank">
        <i class="ri-github-fill ri-xl"></i>
      </a>
      <a href="https://twitter.com/azouaoui_med" target="_blank">
        <i class="ri-twitter-fill ri-xl"></i>
      </a>
      <a href="https://codepen.io/azouaoui-med" target="_blank">
        <i class="ri-codepen-fill ri-xl"></i>
      </a>
      <a href="https://www.linkedin.com/in/mohamed-azouaoui/" target="_blank">
        <i class="ri-linkedin-box-fill ri-xl"></i>
      </a>
    </div>
  </footer>
<div class="overlay"></div>
</div>
</html>

templates/student/includes/navigation.html
<nav class="navbar navbar-expand-lg bg-transparent">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% for item in navbar_titles %}
                    {% if item.sub_menu %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ item.title }}
                            </a>
                            <ul class="dropdown-menu">
                            {% for sub_item in item.sub_menu %}
                                <li>
                                    <a class="dropdown-item" href="#">{{ sub_item }}</a>
                                </li>
                            {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href=".{{ item.url }}">{{ item.title }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>                
        </div>
    </div>
</nav>
<form class="logout-link" action="{% url 'account:logout' %}" method="POST" style="float:right;">
    {% csrf_token %}
    <button class="btn" type="submit">
        <i class="ri-logout-box-r-line"></i>
    Déconnexion</button>
    <!-- <input type="submit" id="deconnect" value="Déconnexion">      -->
</form>  


<!-- <link href="https://unpkg.com/css-pro-layout/dist/css/css-pro-layout.min.css" rel="stylesheet" /> -->
<style>

    .navbar.nav-item {
        font-family: 'Poppins', sans-serif;
        font-weight: 400;
        color:rgb(3, 84, 108) !important;
    }
    body {
        font-family: 'Poppins', sans-serif;
        font-weight: 400;
        color:rgb(3, 84, 108) !important;
    }
    form.logout-link {
        display: inline;
        right: 0;
        width: 100%;
        position: fixed;
    }
    .logout-link {
        float: right;
        right: 0;
        /* text-align: right; */
        margin-right: 20px;
    }

    .btn {
        float: right;
        text-align: right;
        margin-top: 20px;
        color:rgb(3, 84, 108) !important;
        right: 0;
    }

    .nav-item {
        margin-top: 20px;
        margin-left: 60px;
        font-family: 'Poppins', sans-serif;
        font-weight: 400;
        color:rgb(3, 84, 108) !important;
    }
    #deconnect {
        background-color: transparent;
        cursor: pointer;
        color:rgb(3, 84, 108);
        border:none;
        width: 100%;
        margin-left: 300px;
        float: right;
    }
</style>

templates/student/includes/navigation_copy.html
<div class="navbar-layout">
    <ul id="deroulant">
        {% for item in navbar_titles %}
        <li class="{{ item.class }}"> 
            <a href=".{{ item.url }}">
                <span class="menu-title">
                    {{ item.title }}
                </span>
            
            {% if  item.sub_menu  %}
                <ul>
                {% for s in item.sub_menu %}
                    <li class="menu-item">
                        <a href="#">
                        <span class="menu-title">{{ s }}</span>
                        </a>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </a>
        </li>
        {% endfor %}
        
    </ul>
    <ul>
        <li style="float:right; margin-left:0px;right:0;">
            <a>
                <form class="logout-link" action="{% url 'account:logout' %}" method="POST">
                {% csrf_token %}
                <input class="right" type="submit" id="deconnect" value="Déconnexion">
                </form>
            </a>    
        </li>
    </ul>
</div>
<style>

li {
  float: left;
}

.navbar-layout {
        width: 200%;
}
#deconnect {
    float: right;
    display: block;
    text-align: right;
    right:0;
}

#deroulant {
    list-style-type: none;
    overflow: hidden;
    padding: 100;
    margin: 40;  
    text-align: center;
}
    
#deroulant ul {
    position: absolute;
    list-style:none;
    text-align: center;
    width: 220px;
    top: 50px;
    z-index: 5; 
    margin: 40;
    padding: 40;
    border-radius: 4px;
}


#deroulant li{
    border-radius: 4px;
    margin-bottom:4px;
    margin-right: 80px;
    padding: 80;
    float: left;
}

    #deroulant li li {
        max-height:0;
        height:40px;
        z-index: 5;
        overflow: hidden;
        transition: all .5s;
        border-radius: 2px;
        /* background: #444; */
        box-shadow: none;
        border: none;
        margin: 0;
        }
    #deroulant a {
        text-decoration: none;
        position: block;
        font-family: 'Poppins', sans-serif;
        font-size: 1.2em;
        font-weight:500;
        color:rgb(3, 84, 108);
    }

    /* #deroulant li a {
        text-decoration: none;
        display: block;
        text-align: center;
        font-family: 'Poppins', sans-serif;
        font-size: 1.2em;
        font-weight:500;
        color:rgb(3, 84, 108);
    } */
    
    #deroulant li:hover li a {
        font-size:14px;
        text-align: left;
        padding: 10px 10px;
    }
    #deroulant li:hover {
    top: 0;
    }
    /* #deroulant li li:hover {
    background: #93c4e0;
    } */
    #deroulant ul li:last-child {
    border-radius: 2px 2px 2px 2px;
    border:none;
    }

    #deroulant li:hover ul {
    display: block; 
    background: #93c4e0;
    }

    #deroulant li:hover ul li {
    max-height: 5em;
    }

    .navbar-layout  {
        display: flex;
        position: relative;
    }
    .navbar-layout ul {
        display: flex;
        list-style: none;
        position: relative;
        float: left;
    }

    .menu-item {
        margin-left: 10px;
        margin-bottom: 10px;
    }

    .navbar-layout.menu-item {
        float: left;
        margin-right: 60px;
    }
    .navbar-layout.menu-item a {
        text-decoration: none;
        position: relative;
        font-family: 'Poppins', sans-serif;
        font-size: 1.2em;
        font-weight:500;
        color:rgb(3, 84, 108);
    }

    .navbar-layout.menu-item a:after {    
        background: none repeat scroll 0 0 transparent; 
        bottom: 0;
        content: "";
        display: block;
        height: 2px;
        left: 0%;
        position: absolute;
        background: rgb(3, 84, 108);
        transition: width 0.3s ease 0s, left .3s ease 0s;
        width: 0;
    }

    .navbar-layout ul .menu-item a:hover::after { 
        width: 100%; 
        left: 0; 
        content: "";
        display: table;
        clear: both;
    }

    .navbar-layout ul .menu-title a {
            font-size: 0.9em;
            overflow: hidden;
            /* text-overflow: ellipsis; */
            white-space: nowrap;
            flex-grow: 1;
            transition: color 0.3s;
          }

    @media screen and (max-height: 300px) {
            .navbar-layout ul {
                margin-top: 80px;
                margin-right: 10px;
            }
        }

    @media screen and (max-width: 600px) {
            #deconnect {
                float: right;
                width: 100%;
                margin-right: 10px;
            }
            .navbar-layout ul .menu-item  {
                /* margin-top: 40px; */
                margin: 10px;
            }
        }

    body {
        font-family: 'Poppins', sans-serif;
        /* font-size: 1.5em; */
    }

    @keyframes rotate {
        0% {
            transform: rotate(0);
        }
        100% {
            transform: rotate(90deg);
        }
    }

    #deconnect {
        background-color: white;
        cursor: pointer;
        color:rgb(3, 84, 108);
        font-size: 1.2em;
        font-weight: 500;
        font-family: 'Poppins', sans-serif;
        display: block;
        position: block;
        border:none;
        width: 100%;
        margin-left: 300px;
        float: right;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link href="https://unpkg.com/css-pro-layout/dist/css/css-pro-layout.min.css" rel="stylesheet" />

templates/student/includes/sidebar.html
{% load static %}
<!-- <a id="btn-collapse" class="sidebar-collapser"><i id="icon" class="ri-arrow-left-s-line"></i></a> -->
<div class="sidebar-layout">
  <!-- Account header -->
  <div class="sidebar-header">
    <div class="pro-sidebar-logo">
    <div>V</div>
    <h5>Victoria</h5>
  </div>
  </div>
  <div class="sidebar-content">
    <nav class="menu open-current-submenu">
      <ul>
        <li class="menu-header"><span> GENERAL </span></li>
        <li class="menu-item">
        {% for item in sidebar_titles %}
        <a href=".{{ item.url }}">
          <span class="menu-icon">
            <i class="{{ item.icon }}"></i>
          </span>
          <span class="menu-title">{{ item.title }}</span>
        </a>
        {% endfor %}</li>
      </ul>
    </nav>
  </div>
</div>
<style>
  .menu-title {
    text-decoration: none !important;;
  }
</style>

<!-- <link rel="stylesheet"  href="{% static 'student/style.css' %}"/> -->